"""Update session model fields

Revision ID: 62332287bebc
Revises: f49850b71603
Create Date: 2026-04-23 01:42:54.075413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62332287bebc'
down_revision: Union[str, Sequence[str], None] = 'f49850b71603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'notes')
    op.drop_column('sessions', 'end_time')
    op.drop_column('sessions', 'start_time')
    op.drop_column('sessions', 'room_id')
    # ### end Alembic commands ###
